language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true
before_install:
  - composer selfupdate
install:
  - composer update --no-interaction --prefer-source
script:
  - ./bin/behat.phar
notifications:
  email: false
